levelkdev/BC-DAPP

package-lock.json
package.json
public/index.html
src/components/BondingCurveChart.js

setup bonding curve chart with sample data

---

src/App.css
src/App.js
src/components/BondingCurveChart.js
src/components/TradeHistory.js
src/containers/TradeHistoryContainer.js

trade history styling

---

src/App.css
src/App.js
src/components/BondingCurveChart.js
src/components/BuySell.js
src/components/NavBar.js
src/components/TradeHistory.js
src/containers/NavBarContainer.js

Nav Styles

---

src/App.css
src/App.js
src/components/RedeemRewards.js
src/containers/RedeemRewardsContainer.js

rewards styles

---

src/App.js
src/components/BuySell.js
src/components/BuySell/BuyForm.js
src/components/BuySell/SellForm.js

Add Buy and Sell Form components
BuySell tabs interactivity

BuySell Updates

---

src/App.css
src/components/BuySell.js
src/components/BuySell/BuyForm.js
src/components/BuySell/SellEnable.js
src/components/BuySell/SellEnablePending.js

SellEnablePending Panel

---

public/checkbox_758AFE.svg
src/App.css
src/components/BuySell.js
src/components/BuySell/SellContinue.js

SellContinue Panel

---

src/components/BuySell.js
src/components/BuySell/SellForm.js
src/components/common/Form.js

SellForm Panel

---

package-lock.json
package.json
src/components/NavBar.js
src/components/common/Web3ConnectButton.js

start to using web3connect

---

src/components/common/Web3ConnectButton.js

store web3 provider address and other attributes in state

---

src/components/BuySell/BuyForm.js
src/components/BuySell/BuyInput.js
src/components/common/Form.js
src/components/common/InactiveButton.js
src/config.json
src/stores/Provider.js
src/stores/Trading.js

Happy path ERC20 buy flow

---

src/components/TradeHistory.js
src/config.json
src/stores/Provider.js
src/stores/Trading.js

Note: Unit conversion will be addressed in a separate issue/PR.

display trade history

---

src/components/BuySell.js
src/components/Sell/SellConfirmed.js
src/components/Sell/SellSign.js
src/components/Sell/SellUnconfirmed.js
src/stores/Trading.js

Remove the adjustments that were compensating for incorrect deployment of Open Raise contracts.

adjust units in the UI

---

src/components/Buy/BuyConfirmed.js
src/components/Buy/BuySign.js
src/components/Buy/BuyUnconfirmed.js
src/components/TradeHistory.js
src/components/common/Web3ConnectButton.js
src/stores/Provider.js
src/stores/Trading.js

- Update trade data after buy, sell and approve
- Some code cleanup

Update trade data after buy, sell and approve

---

src/components/BondingCurveChart.js
src/components/Buy/BuyConfirmed.js
src/components/Buy/BuyInput.js
src/components/Buy/BuySign.js
src/components/Buy/BuyUnconfirmed.js
src/components/BuySell.js
src/components/NavBar.js
src/components/Sell/SellConfirmed.js
src/components/Sell/SellInput.js
src/components/Sell/SellSign.js
src/components/Sell/SellUnconfirmed.js
src/stores/Provider.js
src/stores/Trading.js
src/utils/bignumber.js

Fix issues

---

package-lock.json
package.json
src/components/common/UserAddress.js

Addresses https://github.com/levelkdev/BC-DAPP/issues/51

Add jazzicon to web3connect pill

---

src/components/BondingCurveChart.js
src/components/Buy/BuyInput.js
src/components/NavBar.js
src/components/Sell/SellInput.js

Buy and sell input style updates,
Addresses https://github.com/levelkdev/BC-DAPP/issues/64
Trade widget error message aligned right,
Addresses https://github.com/levelkdev/BC-DAPP/issues/63
Add back Chartbox elements lost in merge,
Addresses https://github.com/levelkdev/BC-DAPP/issues/60
Fix navbar item spacing,
Addresses https://github.com/levelkdev/BC-DAPP/issues/46

Couple styling fixes

---

src/provider/MetamaskConnector.ts
src/provider/connectors.ts

Fix metamask not detecting previously authorized account

---

src/stores/Provider.ts
src/stores/datStore.ts

Fixes https://github.com/levelkdev/BC-DAPP/issues/74

Trade history time display

---

src/components/Buy/BuyForm.js
src/components/Buy/BuyInput.js

Show connection warning when not connected using buyform

---

src/App.css

Fixes https://github.com/levelkdev/BC-DAPP/issues/96

Make background fill up viewport

---

src/components/Buy/BuySign.js
src/components/Buy/BuyUnconfirmed.js
src/components/common/PendingCircle.tsx
yarn.lock

Addresses buy side for https://github.com/levelkdev/BC-DAPP/issues/66
Will address sell side once https://github.com/levelkdev/BC-DAPP/pull/119 is merged.

Add PendingCircle Component and add to BuySign and BuyUnconfirmed

---

src/components/Buy/BuyConfirmed.tsx
src/components/Buy/BuyInput.js
src/components/Buy/BuySign.js
src/components/Buy/BuyUnconfirmed.js
src/components/Sell/SellConfirmed.js
src/components/Sell/SellInput.js
src/components/Sell/SellSign.js
src/components/Sell/SellUnconfirmed.js
src/components/common/InactiveButton.js

Fixes https://github.com/levelkdev/BC-DAPP/issues/118

Remove onClick from InactiveButton

---

src/components/Buy/BuyConfirmed.tsx
src/components/Buy/BuyInput.js
src/components/Sell/SellConfirmed.js
src/components/Sell/SellForm.js
src/components/Sell/SellInput.js
src/components/Sell/SellSign.js
src/components/Sell/SellUnconfirmed.js
src/stores/BlockchainFetch.ts
src/stores/Token.ts
src/stores/TradingForm.ts
src/stores/datStore.ts

This gets the enable DXD button and Sell working.  Addresses https://github.com/levelkdev/BC-DAPP/issues/73 but will create a couple new issues to address connecting the full Enable flow (with pending panel states) and the price formatting/display.

Enable DXD and Sell Flow Updates

---

src/components/Buy/BuyForm.js
src/components/Buy/BuySign.js
src/components/Buy/BuyUnconfirmed.js

Tokens issued = Buy Amount
Pay = Total

rename buy order description

---

src/components/Buy/BuySign.js
src/components/Buy/BuyUnconfirmed.js
src/components/Sell/SellConfirmed.js
src/components/Sell/SellForm.js
src/components/Sell/SellInput.js
src/components/Sell/SellSign.js
src/components/Sell/SellUnconfirmed.js

add loading animation
renamed orderform descriptions

rename things, add loading indicator for sell

---

src/components/BuySell.js
src/components/NavBar.js
src/components/Sell/SellDisconnected.js
src/components/Web3ConnectStatus/index.jsx

Show connect button in sell when not connected

---

src/components/Buy/BuyInput.js
src/components/Sell/SellDisconnected.js
src/components/Sell/SellInput.js
src/stores/config.ts
src/stores/datStore.ts
src/utils/validators.ts

Fix buy and sellf input in forms accepting only float numbers

---

src/components/Buy/BuyInput.js
src/components/Sell/SellConfirmed.js
src/components/Sell/SellInput.js
src/components/Sell/SellUnconfirmed.js
src/stores/TradingForm.ts

- Fix resetting buy / sell info on invalid input (accidentally removed in a recent PR)
- Fix https://github.com/levelkdev/BC-DAPP/issues/130
- Fix https://github.com/levelkdev/BC-DAPP/issues/128

Jpk sell price

---

src/components/Buy/BuyInput.js
src/components/Sell/SellInput.js

Buttons active in buy and sell only with right conditions

---

src/stores/TradingForm.ts
src/utils/token.tsx

Use 4 decimals precision for all values

---

.env.example
README.md
scripts/deploy.js
scripts/dev.sh
src/provider/connectors.ts
src/stores/config.ts

- Now no need to be switching between env varibales for kovan and develop.

Simplify dev and start commands and env configuration

---

.gitignore
scripts/deploy.js
scripts/deployDAT.js
src/components/Footer.js
src/config/contracts.json

- The footer now shows the commit hash, version, DATProxy address and DAT implementation address urs.
- src/contracts added to .gitignore.

Update footer and add src/contracts to gitignore

---

src/App.js
src/components/NavBar.js

fixes https://github.com/levelkdev/BC-DAPP/issues/172

remove navbar items

---

src/provider/connectors.ts

When you are in develop and metamask is not connected to localhost it was getting the wrong backup localhost url.

Fix typo and backup url in develop

---

src/components/BuySell.js
src/components/BuySellTabs.js
src/components/Sell/SellConfirmed.js
src/components/Sell/SellInput.js
src/components/Sell/SellSign.js
src/components/Sell/SellUnconfirmed.js

Addresses https://github.com/levelkdev/BC-DAPP/issues/77

BuySell displays withdraw when in init period

---

src/components/Buy/BuyInput.js
src/components/Sell/SellInput.js

fix(buysell): Reset values between buy/sell tabs

---

.gitignore
src/config/contracts.json

Ignore src/confog.contracts.json

---

README.md
package.json
tslint.json
yarn.lock

prettier + tslint on commit

---

.env.example
README.md
public/index.html

Fix few small issues and update readme.

Improve readme

---

package.json
scripts/start.sh

Fix error when running yarn start without compiling contracts first.

Add start.sh script

---

src/App.js
src/components/Footer.js
src/components/LandingPage/Footer.js
src/components/LandingPage/LandingPage.js
src/containers/LandingPageContainer.js

- Shows landing page at / view.

Show landing page at index

---

public/checkbox_758AFE.svg
src/components/Enable/EnableContinue.js
src/components/Enable/EnablePending.js
src/components/Sell/SellDisconnected.js
src/components/common/PendingCircle.tsx

Fixes https://github.com/levelkdev/BC-DAPP/issues/68

Loading circle

---

src/components/BuySell.js
src/stores/BlockchainFetch.ts
tslint.json

Fix input field reset

---

src/components/Buy/BuyConfirmed.tsx
src/components/Buy/BuyInput.js
src/components/Buy/BuySign.js
src/components/Buy/BuyUnconfirmed.js
src/components/Sell/SellConfirmed.js
src/components/Sell/SellInput.js
src/stores/TradingForm.ts

* Show previous buy & sell information after respective trade confirmations
Fix #246 #259

Show previous buy info on 'buy again' panel

---

src/components/NavBar.js
src/components/TradeHistory.js
src/components/WalletModal/index.js
src/components/Web3ReactManager/index.tsx

- fix(web3ReactManager): Change 600 miliseconds for 3000 to check backup connection status
- fix(tradeHistory): Have unique key in each tradeRow element
- fix(navbar): Simplify navbar with only one optin and clear error messages

Clear conlose errors

---

src/components/BuySellTabs.js

fixes: https://github.com/levelkdev/BC-DAPP/issues/263

fix inactive buy tab rounding corner

---

.openzeppelin/kovan.json
README.md
scripts/deployContracts.js

- Add governance section in readme.
- Add kovan deploy.
Deployment log:
```
Using account: 0xC4B60a931929d3ed0AC423F9Ea80e5962726dA73  
Deploy DAT with config: {
"collateralType": "ETH",
"name": "DXdao",
"symbol": "DXD",
"currency": "0x0000000000000000000000000000000000000000",
"whitelist": "0x0000000000000000000000000000000000000000",
"initReserve": "100000000000000000000000",
"initGoal": "4898979485566395000000",
"buySlopeNum": "1",
"buySlopeDen": "48000000000000000000000",
"investmentReserveBasisPoints": "1000",
"revenueCommitmentBasisPoints": "1000",
"minInvestment": "1000000000000000",
"feeBasisPoints": "0",
"autoBurn": true,
"openUntilAtLeast": 1683171717,
"control": "0x0468eBA33b191C8A3C5eB5d62714fFFa155BCF52",
"beneficiary": "0x0468eBA33b191C8A3C5eB5d62714fFFa155BCF52", …
```

Add official kovan dev deploy

---

contracts/utils/DecentralizedAutonomousTrustUpgrade.sol
scripts/testUpgradeability.js

Log of script executed successfully on kovan:
```
Using account: 0xC4B60a931929d3ed0AC423F9Ea80e5962726dA73  
Deploy DAT with config: {
"collateralType": "ETH",
"name": "DXdao",
"symbol": "DXD",
"currency": "0x0000000000000000000000000000000000000000",
"whitelist": "0x0000000000000000000000000000000000000000",
"initReserve": "100000000000000000000000",
"initGoal": "4898979485566395000000",
"buySlopeNum": "1",
"buySlopeDen": "48000000000000764000000",
"investmentReserveBasisPoints": "1000",
"revenueCommitmentBasisPoints": "1000",
"minInvestment": "1000000000000000",
"feeBasisPoints": "0",
"autoBurn": true,
"openUntilAtLeast": 1746329585,
"control": "0xC4B60a931929d3ed0AC423F9Ea80e5962726dA73",
"beneficiary": "0x519b70055af55a007110b4ff99b0ea33071c720a",
"feeCollector": …
```

Adds quick script to test upgradeability

---

src/components/Footer.js

fixes: https://github.com/levelkdev/BC-DAPP/issues/314

rename proxy to token contract and contract to local contract

---

.openzeppelin/mainnet.json
scripts/deployContracts.js

Add the mainnet contracts that were deployed, transferred and accepted by the DXdao.

Add mainnet contracts used for v0.2.0 deployment

---

src/components/LandingPage/LandingPage.js

fixes: 
https://github.com/levelkdev/BC-DAPP/issues/315
https://github.com/levelkdev/BC-DAPP/issues/319

add omen hyperlink and fix typo

---

package.json
scripts/deploy.js
scripts/dev.sh
scripts/loadDeployments.js
src/components/Footer.js
src/components/LandingPage/Footer.js
src/stores/datStore.ts

- Adds the fromBlock value to be used finto the contracts.json file in src.
- Get only the trades form the last 1000 blocks.

Get only trade events from last 1000 blocks

---

scripts/dev.sh
scripts/loadDeployments.js
src/stores/datStore.ts

Get trade events form last 50k blocks, make request for every 5k blocks, if it reaches the trade event limit stop fetching, it ti reaches the block limit it stops searching too.

Sequential event fecth
